///////////////////////////////////////////////////////////////////////////////
///(c) kuiash.com ltd 2017+ code@kuiash.com ///////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
var x = require('xml');
///////////////////////////////////////////////////////////////////////////////
module.exports = {
    'a': function() { return x.el('a', ...arguments) },
    'abbr': function() { return x.el('abbr', ...arguments) },
    'acronym': function() { return x.el('acronym', ...arguments) },
    'address': function() { return x.el('address', ...arguments) },
    'applet': function() { return x.el('applet', ...arguments) },
    'area': function() { return x.el('area', ...arguments) },
    'article': function() { return x.el('article', ...arguments) },
    'aside': function() { return x.el('aside', ...arguments) },
    'audio': function() { return x.el('audio', ...arguments) },
    'b': function() { return x.el('b', ...arguments) },
    'base': function() { return x.el('base', ...arguments) },
    'basefont': function() { return x.el('basefont', ...arguments) },
    'bdi': function() { return x.el('bdi', ...arguments) },
    'bdo': function() { return x.el('bdo', ...arguments) },
    'big': function() { return x.el('big', ...arguments) },
    'blockquote': function() { return x.el('blockquote', ...arguments) },
    'body': function() { return x.el('body', ...arguments) },
    'br': function() { return x.el('br', ...arguments) },
    'button': function() { return x.el('button', ...arguments) },
    'canvas': function() { return x.el('canvas', ...arguments) },
    'caption': function() { return x.el('caption', ...arguments) },
    'center': function() { return x.el('center', ...arguments) },
    'cite': function() { return x.el('cite', ...arguments) },
    'code': function() { return x.el('code', ...arguments) },
    'col': function() { return x.el('col', ...arguments) },
    'colgroup': function() { return x.el('colgroup', ...arguments) },
    'datalist': function() { return x.el('datalist', ...arguments) },
    'dd': function() { return x.el('dd', ...arguments) },
    'del': function() { return x.el('del', ...arguments) },
    'details': function() { return x.el('details', ...arguments) },
    'dfn': function() { return x.el('dfn', ...arguments) },
    'dialog': function() { return x.el('dialog', ...arguments) },
    'dir': function() { return x.el('dir', ...arguments) },
    'div': function() { return x.el('div', ...arguments) },
    'dl': function() { return x.el('dl', ...arguments) },
    'dt': function() { return x.el('dt', ...arguments) },
    'em': function() { return x.el('em', ...arguments) },
    'embed': function() { return x.el('embed', ...arguments) },
    'fieldset': function() { return x.el('fieldset', ...arguments) },
    'figcaption': function() { return x.el('figcaption', ...arguments) },
    'figure': function() { return x.el('figure', ...arguments) },
    'font': function() { return x.el('font', ...arguments) },
    'footer': function() { return x.el('footer', ...arguments) },
    'form': function() { return x.el('form', ...arguments) },
    'frame': function() { return x.el('frame', ...arguments) },
    'frameset': function() { return x.el('frameset', ...arguments) },
    'h1': function() { return x.el('h1', ...arguments) },
    'h2': function() { return x.el('h2', ...arguments) },
    'h3': function() { return x.el('h3', ...arguments) },
    'h4': function() { return x.el('h4', ...arguments) },
    'head': function() { return x.el('head', ...arguments) },
    'header': function() { return x.el('header', ...arguments) },
    'hr': function() { return x.el('hr', ...arguments) },
    'html': function() { return x.el('html', ...arguments) },
    'i': function() { return x.el('i', ...arguments) },
    'iframe': function() { return x.el('iframe', ...arguments) },
    'img': function() { return x.el('img', ...arguments) },
    'input': function() { return x.el('input', ...arguments) },
    'ins': function() { return x.el('ins', ...arguments) },
    'kbd': function() { return x.el('kbd', ...arguments) },
    'keygen': function() { return x.el('keygen', ...arguments) },
    'label': function() { return x.el('label', ...arguments) },
    'legend': function() { return x.el('legend', ...arguments) },
    'li': function() { return x.el('li', ...arguments) },
    'link': function() { return x.uc('link', ...arguments) },
    'main': function() { return x.el('main', ...arguments) },
    'map': function() { return x.el('map', ...arguments) },
    'mark': function() { return x.el('mark', ...arguments) },
    'menu': function() { return x.el('menu', ...arguments) },
    'menuitem': function() { return x.el('menuitem', ...arguments) },
    'meta': function() { return x.uc('meta', ...arguments) },
    'meter': function() { return x.el('meter', ...arguments) },
    'nav': function() { return x.el('nav', ...arguments) },
    'noframes': function() { return x.el('noframes', ...arguments) },
    'noscript': function() { return x.el('noscript', ...arguments) },
    'object': function() { return x.el('object', ...arguments) },
    'ol': function() { return x.el('ol', ...arguments) },
    'optgroup': function() { return x.el('optgroup', ...arguments) },
    'option': function() { return x.el('option', ...arguments) },
    'output': function() { return x.el('output', ...arguments) },
    'p': function() { return x.el('p', ...arguments) },
    'param': function() { return x.el('param', ...arguments) },
    'picture': function() { return x.el('picture', ...arguments) },
    'pre': function() { return x.el('pre', ...arguments) },
    'progress': function() { return x.el('progress', ...arguments) },
    'q': function() { return x.el('q', ...arguments) },
    'rp': function() { return x.el('rp', ...arguments) },
    'rt': function() { return x.el('rt', ...arguments) },
    'ruby': function() { return x.el('ruby', ...arguments) },
    's': function() { return x.el('s', ...arguments) },
    'samp': function() { return x.el('samp', ...arguments) },
    'script': function() { return x.el('script', ...arguments) },
    'section': function() { return x.el('section', ...arguments) },
    'select': function() { return x.el('select', ...arguments) },
    'small': function() { return x.el('small', ...arguments) },
    'source': function() { return x.el('source', ...arguments) },
    'span': function() { return x.el('span', ...arguments) },
    'strike': function() { return x.el('strike', ...arguments) },
    'strong': function() { return x.el('strong', ...arguments) },
    'style': function() { return x.el('style', ...arguments) },
    'sub': function() { return x.el('sub', ...arguments) },
    'summary': function() { return x.el('summary', ...arguments) },
    'sup': function() { return x.el('sup', ...arguments) },
    'table': function() { return x.el('table', ...arguments) },
    'tbody': function() { return x.el('tbody', ...arguments) },
    'td': function() { return x.el('td', ...arguments) },
    'textarea': function() { return x.el('textarea', ...arguments) },
    'tfoot': function() { return x.el('tfoot', ...arguments) },
    'th': function() { return x.el('th', ...arguments) },
    'thead': function() { return x.el('thead', ...arguments) },
    'time': function() { return x.el('time', ...arguments) },
    'title': function() { return x.el('title', ...arguments) },
    'tr': function() { return x.el('tr', ...arguments) },
    'track': function() { return x.el('track', ...arguments) },
    'tt': function() { return x.el('tt', ...arguments) },
    'u': function() { return x.el('u', ...arguments) },
    'ul': function() { return x.el('ul', ...arguments) },
    'var': function() { return x.el('var', ...arguments) },
    'video': function() { return x.el('video', ...arguments) },
    'wbr': function() { return x.el('wbr', ...arguments) },
    // Speciality functions
    'cssinc': function(url) { return x.el('link', { href: url, 'rel': 'stylesheet' }, '') },
    'jsinc': function(href) { return x.el('script', { 'type': 'text/javascript', 'src': href }, '') },
    'jsraw': function(raw) { return x.el('script', { 'type': 'text/javascript' }, x.xr(raw)) },
    'jsasd': function(raw) { return x.el('script', { 'type': 'text/javascript', 'async':null, 'defer':null }, x.xr(raw)) },
}
///////////////////////////////////////////////////////////////////////////////
